import { defineConfig } from "oxlint";

// Server-side subset of the crauler/igerslike rules. Layout rules come from oxlint-plugin-arch,
// so do not add a formatter (oxfmt/prettier would fight them).
const restrictedSyntax = [
  {
    selector: "CallExpression[callee.object.name=\"Promise\"][callee.property.name=\"all\"] ArrayExpression MemberExpression[property.name=\"push\"]",
    message: "Avoid push() inside Promise.all(). Return values from the async function instead.",
  },
  {
    selector: "BinaryExpression[operator='in'][left.type='Literal'][left.raw=/^['\"].*['\"]$/]",
    message: "Avoid string-literal `in` checks. Use a typed shape, Object.hasOwn() or a discriminated branch.",
  },
  {
    selector: "CallExpression[callee.object.name=\"console\"][callee.property.name=\"log\"]",
    message: "Do not use console.log. Use console.error for failures worth logging.",
  },
  {
    selector: "SwitchStatement",
    message: "Do not use switch statements. Use a lookup object or early returns.",
  },
  {
    selector: "TSUnknownKeyword",
    message: "Do not use unknown. Type the boundary instead.",
  },
];

export default defineConfig({
  options: {
    typeAware: true,
    denyWarnings: true,
  },
  plugins: ["typescript", "import", "unicorn", "promise", "vitest", "node", "oxc"],
  jsPlugins: [
    { name: "eslint-js", specifier: "oxlint-plugin-eslint" },
    { name: "import-extra", specifier: "eslint-plugin-import" },
    { name: "arch", specifier: "oxlint-plugin-arch" },
    "@regru/eslint-plugin-prefer-early-return",
    "eslint-plugin-unused-imports",
    "eslint-plugin-perfectionist",
    "@eslint-community/eslint-plugin-eslint-comments",
  ],
  categories: {},
  rules: {
    "for-direction": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-console": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-else-if": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-global-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-prototype-builtins": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",

    "array-callback-return": "error",
    "default-case-last": "error",
    eqeqeq: "error",
    "no-alert": "error",
    "no-caller": "error",
    "no-constructor-return": "error",
    "no-else-return": "warn",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-param-reassign": "error",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-return": "warn",
    "no-useless-computed-key": "warn",
    "no-useless-rename": "warn",
    "no-var": "error",
    "object-shorthand": "warn",
    "prefer-const": "error",
    "prefer-numeric-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "symbol-description": "error",
    "no-promise-executor-return": "error",
    "no-template-curly-in-string": "error",
    "new-cap": ["error", { capIsNew: false }],
    "no-lonely-if": "warn",
    "no-multi-assign": "error",
    "no-nested-ternary": "error",
    "no-unneeded-ternary": "error",
    "prefer-object-spread": "warn",
    "no-label-var": "error",
    "no-await-in-loop": "error",
    curly: "error",
    "max-lines": ["warn", { max: 400, skipBlankLines: true, skipComments: true }],
    complexity: ["warn", { max: 32 }],

    "typescript/await-thenable": "error",
    "typescript/no-array-constructor": "error",
    "typescript/no-base-to-string": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-duplicate-type-constituents": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-meaningless-void-operator": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-misused-spread": "error",
    "typescript/no-mixed-enums": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-redundant-type-constituents": "warn",
    "typescript/no-require-imports": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-boolean-literal-compare": "error",
    "typescript/no-unnecessary-condition": "warn",
    "typescript/no-unnecessary-template-expression": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-unary-minus": "error",
    "typescript/no-unused-expressions": "error",
    "no-unused-vars": [
      "error",
      {
        args: "after-used",
        argsIgnorePattern: "^_",
        ignoreRestSiblings: false,
        vars: "all",
        varsIgnorePattern: "^_",
      },
    ],
    "typescript/no-useless-constructor": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/restrict-plus-operands": "error",
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/triple-slash-reference": "error",
    "typescript/unbound-method": "off",
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": "error",
    "typescript/ban-tslint-comment": "error",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": "error",
    "typescript/consistent-type-imports": [
      "error",
      {
        prefer: "type-imports",
        disallowTypeAnnotations: true,
        fixStyle: "separate-type-imports",
      },
    ],
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-empty-function": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-includes": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-regexp-exec": "warn",
    "typescript/prefer-string-starts-ends-with": "error",
    "typescript/consistent-type-exports": "warn",
    "typescript/require-array-sort-compare": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/default-param-last": "error",
    "typescript/no-loop-func": "error",
    "typescript/no-shadow": "warn",
    "typescript/ban-ts-comment": "off",
    "typescript/no-explicit-any": "off",

    "import/first": "error",
    "import/no-absolute-path": "error",
    "import/no-mutable-exports": "error",
    "import/no-self-import": "error",
    "import/no-duplicates": "warn",
    "import/no-named-as-default": "warn",
    "import/no-named-as-default-member": "warn",
    "import/consistent-type-specifier-style": "error",

    "unicorn/filename-case": ["error", { case: "kebabCase" }],
    "unicorn/prefer-at": "error",
    "unicorn/prefer-node-protocol": "warn",

    "oxc/no-accumulating-spread": "error",
    "oxc/missing-throw": "error",
    "oxc/erasing-op": "error",
    "oxc/const-comparisons": "error",
    "oxc/double-comparisons": "error",

    "eslint-js/no-restricted-syntax": ["error", ...restrictedSyntax],
    "@regru/prefer-early-return/prefer-early-return": ["error", { maximumStatements: 1 }],
    "unused-imports/no-unused-imports": "error",
    "@eslint-community/eslint-comments/no-aggregating-enable": "error",
    "@eslint-community/eslint-comments/no-duplicate-disable": "error",
    "@eslint-community/eslint-comments/no-unused-enable": "error",
    "import-extra/no-useless-path-segments": "error",
    "import-extra/newline-after-import": "error",

    "arch/no-literal-in": "error",
    "arch/no-promise-all-mutation": "error",
    "arch/padding-between-statements": "error",
    "arch/object-multiline": "error",
    "arch/key-value-same-line": "error",
    "arch/call-array-multiline": "error",
    "arch/chain-newline": ["error", {
      groups: [
        { minDepth: 3, methods: ["map", "filter", "reduce", "flatMap", "find", "some", "every", "sort"] },
      ],
    }],

    "perfectionist/sort-imports": ["error", {
      type: "natural",
      ignoreCase: true,
      newlinesBetween: 0,
      environment: "bun",
      groups: [
        ["builtin", "external"],
        "internal",
        ["parent", "sibling", "index"],
        "type",
      ],
    }],
    "perfectionist/sort-named-imports": ["error", {
      type: "natural",
      ignoreCase: true,
    }],

    "eslint-js/indent": ["error", 2, { MemberExpression: 1, SwitchCase: 1, flatTernaryExpressions: true }],
    "eslint-js/semi": ["error", "always"],
    "eslint-js/quotes": ["error", "double", { avoidEscape: true }],
    "eslint-js/comma-dangle": ["error", "always-multiline"],
    "eslint-js/no-trailing-spaces": "error",
    "eslint-js/no-multiple-empty-lines": ["error", { max: 1 }],
    "eslint-js/eol-last": ["error", "always"],
    "eslint-js/no-multi-spaces": "error",

    "eslint-js/arrow-spacing": "error",
    "eslint-js/block-spacing": "error",
    "eslint-js/comma-spacing": ["error", { before: false, after: true }],
    "eslint-js/key-spacing": ["error", { beforeColon: false, afterColon: true }],
    "eslint-js/keyword-spacing": ["error", { before: true, after: true }],
    "eslint-js/object-curly-spacing": ["error", "always"],
    "eslint-js/semi-spacing": ["error", { before: false, after: true }],
    "eslint-js/space-before-blocks": "error",
    "eslint-js/space-before-function-paren": ["error", { anonymous: "always", named: "never", asyncArrow: "always" }],
    "eslint-js/space-infix-ops": "error",
    "eslint-js/space-in-parens": ["error", "never"],
    "eslint-js/template-curly-spacing": ["error", "never"],
    "eslint-js/rest-spread-spacing": ["error", "never"],
    "eslint-js/computed-property-spacing": ["error", "never"],

    "eslint-js/brace-style": ["error", "1tbs", { allowSingleLine: false }],
    "eslint-js/arrow-parens": ["error", "always"],
    "eslint-js/no-extra-semi": "error",
    "eslint-js/no-floating-decimal": "error",
    "eslint-js/dot-location": ["error", "property"],
    "eslint-js/no-whitespace-before-property": "error",
    "eslint-js/object-curly-newline": ["error", { consistent: true }],
    "eslint-js/object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],

    "eslint-js/max-len": ["warn", { code: 160, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true, ignoreRegExpLiterals: true, ignoreComments: true }],
  },
  overrides: [
    {
      files: ["**/apps/*/src/**"],
      rules: {
        "no-console": ["error", { allow: ["error"] }],
        "typescript/no-explicit-any": "error",
      },
    },
    {
      files: ["**/apps/worker/src/worker.ts"],
      rules: {
        "max-lines": ["warn", { max: 700, skipBlankLines: true, skipComments: true }],
      },
    },
    {
      files: ["**/*.types.ts"],
      rules: {
        "arch/no-top-level-functions": ["error", { banReExports: false }],
      },
    },
    {
      files: ["**/tests/**", "**/*.test.ts"],
      rules: {
        "max-lines": "off",
        complexity: "off",
        "vitest/expect-expect": "off",
        "vitest/no-conditional-expect": "off",
        "vitest/require-mock-type-parameters": "off",
        "arch/test-title-pattern": ["error", { forbid: "^should\\b", flags: "i" }],
      },
    },
    {
      files: ["**/scripts/**"],
      rules: {
        "no-console": "off",
        "no-alert": "off",
        "eslint-js/no-restricted-syntax": ["error", ...restrictedSyntax.filter((rule) => !rule.selector.includes("console"))],
      },
    },
  ],
  ignorePatterns: [
    "node_modules",
    "dist",
    ".wrangler",
    ".turbo",
    ".agents/**",
    ".claude/**",
    "**/worker-configuration.d.ts",
  ],
});
